/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_db;

import Controlador.ControladorServicio;

/**
 *
 * @author diego
 */
public class ActualizarServicio extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarServicio
     */
    static SolicitarServicio ss;
    String datoAactualizar;
    String dato;
    ControladorServicio servicio;

    public ActualizarServicio() {
        initComponents();

    }

    public ActualizarServicio(SolicitarServicio ss) {
        this.ss = ss;
        ss = new SolicitarServicio();
        initComponents();
        buttonGroup1.add(radioMoto);
        buttonGroup1.add(radioId);
        buttonGroup1.add(radioCarro);
        buttonGroup1.add(radioCamion);
        buttonGroup1.add(RadioDireccionOrigen);
        buttonGroup1.add(radioCiuOrigen);
        buttonGroup1.add(radiociudaddestino);
        buttonGroup1.add(RadioDireccionDestino);
        buttonGroup1.add(radioDescripcion);
        buttonGroup1.add(RadioNumPaquetes);
    }

    public void elegirDato() {
        if (buttonGroup1.getSelection() == radiociudaddestino.getModel()) {
            datoAactualizar = "ciudad_destino";
            TFDato.setEnabled(true);
        } else if (buttonGroup1.getSelection() == RadioDireccionDestino.getModel()) {
            datoAactualizar = "direccion_destino";
            TFDato.setEnabled(true);
        } else if (buttonGroup1.getSelection() == radioCiuOrigen.getModel()) {
            datoAactualizar = "ciudad_origen";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == RadioDireccionOrigen.getModel()) {
            datoAactualizar = "direccion_origen";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == radioCarro.getModel()) {
            datoAactualizar = "tipo_transporte=carro";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == radioMoto.getModel()) {
            datoAactualizar = "tipo_transporte=moto";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == radioCamion.getModel()) {
            datoAactualizar = "tipo_transporte=camion";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == radioDescripcion.getModel()) {
            datoAactualizar = "descripcion";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == radioId.getModel()) {
            datoAactualizar = "mensajero_id";
            TFDato.setEnabled(true);

        } else if (buttonGroup1.getSelection() == RadioNumPaquetes.getModel()) {
            datoAactualizar = "num_paquetes";
            TFDato.setEnabled(true);

        }
    }

    public void activarTFActualizar() {
        if (datoAactualizar != null) {
            TFDato.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioId = new javax.swing.JRadioButton();
        radioDescripcion = new javax.swing.JRadioButton();
        radioCiuOrigen = new javax.swing.JRadioButton();
        radiociudaddestino = new javax.swing.JRadioButton();
        RadioDireccionOrigen = new javax.swing.JRadioButton();
        RadioDireccionDestino = new javax.swing.JRadioButton();
        RadioNumPaquetes = new javax.swing.JRadioButton();
        radioMoto = new javax.swing.JRadioButton();
        radioCarro = new javax.swing.JRadioButton();
        radioCamion = new javax.swing.JRadioButton();
        TFDato = new javax.swing.JTextField();
        lDatoACambiar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bAtras.setText("Atrás");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Pedido #: "+ ss.getTFIDPedido().getText() );

        jLabel2.setText("Qué vas a cambiar?");

        radioId.setText("ID Mensajero");
        radioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdActionPerformed(evt);
            }
        });

        radioDescripcion.setText("Descripción");
        radioDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDescripcionActionPerformed(evt);
            }
        });

        radioCiuOrigen.setText("Ciudad origen");
        radioCiuOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCiuOrigenActionPerformed(evt);
            }
        });

        radiociudaddestino.setText("Ciudad destino");
        radiociudaddestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiociudaddestinoActionPerformed(evt);
            }
        });

        RadioDireccionOrigen.setText("Direccion origen");
        RadioDireccionOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDireccionOrigenActionPerformed(evt);
            }
        });

        RadioDireccionDestino.setText("Direccion destino");
        RadioDireccionDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioDireccionDestinoActionPerformed(evt);
            }
        });

        RadioNumPaquetes.setText("# Paquetes");
        RadioNumPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNumPaquetesActionPerformed(evt);
            }
        });

        radioMoto.setText("Moto");
        radioMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMotoActionPerformed(evt);
            }
        });

        radioCarro.setText("Carro");
        radioCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCarroActionPerformed(evt);
            }
        });

        radioCamion.setText("Camion");
        radioCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCamionActionPerformed(evt);
            }
        });

        TFDato.setEnabled(false);
        TFDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDatoActionPerformed(evt);
            }
        });
        TFDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDatoKeyReleased(evt);
            }
        });

        lDatoACambiar.setText("No hay seleccíon aún");

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RadioNumPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar))
                    .addComponent(bAtras)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiociudaddestino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioCiuOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RadioDireccionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFDato, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(lDatoACambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bAtras)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lDatoACambiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioId)
                    .addComponent(RadioDireccionDestino)
                    .addComponent(TFDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDescripcion)
                    .addComponent(RadioNumPaquetes)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCiuOrigen)
                    .addComponent(radioMoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiociudaddestino)
                    .addComponent(radioCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioDireccionOrigen)
                    .addComponent(radioCamion))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDatoActionPerformed

    }//GEN-LAST:event_TFDatoActionPerformed

    private void radiociudaddestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiociudaddestinoActionPerformed
        elegirDato();
    }//GEN-LAST:event_radiociudaddestinoActionPerformed

    private void radioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIdActionPerformed
        elegirDato();
    }//GEN-LAST:event_radioIdActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        servicio = new ControladorServicio();
        dato = TFDato.getText();
        System.out.println(dato);
        System.out.println(datoAactualizar);
        servicio.ActualizarServicio(ss.getTFIDPedido().getText(), datoAactualizar, dato);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void radioDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDescripcionActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDescripcionActionPerformed

    private void radioCiuOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCiuOrigenActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCiuOrigenActionPerformed

    private void RadioDireccionOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDireccionOrigenActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioDireccionOrigenActionPerformed

    private void RadioDireccionDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioDireccionDestinoActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioDireccionDestinoActionPerformed

    private void RadioNumPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNumPaquetesActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNumPaquetesActionPerformed

    private void radioMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMotoActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMotoActionPerformed

    private void radioCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCarroActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCarroActionPerformed

    private void radioCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCamionActionPerformed
        elegirDato();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCamionActionPerformed

    private void TFDatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDatoKeyReleased
        activarBtnActualizar();
    }//GEN-LAST:event_TFDatoKeyReleased

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAtrasActionPerformed
    public void activarBtnActualizar() {
        if (datoAactualizar != null && TFDato.getText().length() != 0) {
            btnActualizar.setEnabled(true);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioDireccionDestino;
    private javax.swing.JRadioButton RadioDireccionOrigen;
    private javax.swing.JRadioButton RadioNumPaquetes;
    private javax.swing.JTextField TFDato;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton btnActualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lDatoACambiar;
    private javax.swing.JRadioButton radioCamion;
    private javax.swing.JRadioButton radioCarro;
    private javax.swing.JRadioButton radioCiuOrigen;
    private javax.swing.JRadioButton radioDescripcion;
    private javax.swing.JRadioButton radioId;
    private javax.swing.JRadioButton radioMoto;
    private javax.swing.JRadioButton radiociudaddestino;
    // End of variables declaration//GEN-END:variables
}
