/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_db;

import Controlador.ControladorMensajero;

/**
 *
 * @author diego
 */
public class ActualizarMensajero extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarMensajero
     */
    static GestionMensajero gm ;
    String datoAactualizar;
    String dato;
    ControladorMensajero mensajero;

    public ActualizarMensajero() {
        initComponents();
    }
       // Modificar constructor para aceptar una instancia de GestionMensajero
    public ActualizarMensajero(GestionMensajero gm) {
        this.gm = gm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LabelNombreMensajero = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnNombre = new javax.swing.JButton();
        BtanDireccion = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BtnEmail = new javax.swing.JButton();
        LDatoAModificar = new javax.swing.JLabel();
        TFDato = new javax.swing.JTextField();
        btnctualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNombreMensajero.setText("Mensajero: "+ gm.getTFconsultar().getText());

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Dato a actualizar");

        BtnNombre.setText("Nombre");
        BtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNombreActionPerformed(evt);
            }
        });

        BtanDireccion.setText("Dirección");
        BtanDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtanDireccionActionPerformed(evt);
            }
        });

        jButton3.setText("Teléfono");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });

        BtnEmail.setText("Email");
        BtnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmailActionPerformed(evt);
            }
        });

        LDatoAModificar.setText("No hay selección aún");

        TFDato.setEnabled(false);
        TFDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDatoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDatoKeyTyped(evt);
            }
        });

        btnctualizar.setText("Actualizar");
        btnctualizar.setEnabled(false);
        btnctualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombreMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnNombre)
                                .addGap(18, 18, 18)
                                .addComponent(BtanDireccion)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(BtnEmail)
                            .addComponent(LDatoAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFDato, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnctualizar)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BtnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelNombreMensajero)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNombre)
                    .addComponent(BtanDireccion)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEmail)
                        .addGap(18, 18, 18)
                        .addComponent(LDatoAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnctualizar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed

        gm.setVisible(true);

    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNombreActionPerformed
        LDatoAModificar.setText("Nuevo nombre");
        datoAactualizar = "nombre";
        TFDato.setText("");
        activarTFActualizar();

    }//GEN-LAST:event_BtnNombreActionPerformed

    private void BtanDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtanDireccionActionPerformed
        LDatoAModificar.setText("Nueva dirección");
        datoAactualizar = "direccion";
        TFDato.setText("");

        activarTFActualizar();
    }//GEN-LAST:event_BtanDireccionActionPerformed

    public String getDatoAactualizar() {
        return datoAactualizar;
    }

    public String getDato() {
        return dato;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LDatoAModificar.setText("Nuevo teléfono");
        datoAactualizar = "telefono";
        TFDato.setText("");

        activarTFActualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmailActionPerformed
        LDatoAModificar.setText("Nuevo email");
        datoAactualizar = "email";
        TFDato.setText("");

        activarTFActualizar();
    }//GEN-LAST:event_BtnEmailActionPerformed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased

    }//GEN-LAST:event_jButton3KeyReleased

    private void TFDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDatoKeyTyped
        if ("telefono".equals(datoAactualizar)) {
            int key = evt.getKeyChar();

            boolean numeros = key >= 48 && key <= 57;

            if (!numeros) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_TFDatoKeyTyped

    private void TFDatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDatoKeyReleased
        activarBtnActualizar();

    }//GEN-LAST:event_TFDatoKeyReleased

    private void btnctualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctualizarActionPerformed
        mensajero = new ControladorMensajero();
        dato = TFDato.getText();
        mensajero.ActualizarMensajero(gm.TFconsultar.getText() , datoAactualizar, dato);
    }//GEN-LAST:event_btnctualizarActionPerformed
    public void activarBtnActualizar() {
        if (datoAactualizar != null && TFDato.getText().length() != 0) {
            btnctualizar.setEnabled(true);

        }

    }

    public void activarTFActualizar() {
        if (datoAactualizar != null) {
            TFDato.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarMensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarMensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarMensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarMensajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarMensajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtanDireccion;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnEmail;
    private javax.swing.JButton BtnNombre;
    private javax.swing.JLabel LDatoAModificar;
    private javax.swing.JLabel LabelNombreMensajero;
    private javax.swing.JTextField TFDato;
    private javax.swing.JButton btnctualizar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
