/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_db;

import javax.swing.table.DefaultTableModel;
import controlador.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andresuv
 */
public class PgestionarCliente extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ControladorCliente cont = new ControladorCliente();

    /**
     * Creates new form gestionarCliente
     */
    public PgestionarCliente() {
        initComponents();
        String[] titulo = new String[]{"cliente_id", "nombre", "email", "direccion", "telefono", "estado"};
        dtm.setColumnIdentifiers(titulo);
        Tabla.setModel(dtm);

    }

    void llenarT() {
        dtm.addRow(new Object[]{
            Tcliente_id.getText(),
            Tnombre.getText(),
            Temail.getText(),
            Tdireccion.getText(),
            Ttelefono.getText(),
            "Activo"

        });
    }

    void llenarClienteT(String[] cl) {
        dtm.getDataVector().removeAllElements();
        dtm.addRow(new Object[]{cl[0], cl[1], cl[2], cl[3], cl[4], cl[5]});

    }

    void llenarTabla(ResultSet tabla) {
        dtm.getDataVector().removeAllElements();
        try {
            while (tabla.next()) {
                dtm.addRow(new Object[]{
                    tabla.getString(1),
                    tabla.getString(5),
                    tabla.getString(3),
                    tabla.getString(4),
                    tabla.getString(2),
                    tabla.getString(6)
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(PgestionarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lcliente_id = new javax.swing.JLabel();
        Tcliente_id = new javax.swing.JTextField();
        Lnombre = new javax.swing.JLabel();
        Tnombre = new javax.swing.JTextField();
        Lemail = new javax.swing.JLabel();
        Temail = new javax.swing.JTextField();
        Ldireccion = new javax.swing.JLabel();
        Tdireccion = new javax.swing.JTextField();
        Ltelefono = new javax.swing.JLabel();
        Ttelefono = new javax.swing.JTextField();
        Bguardar = new javax.swing.JButton();
        Bbuscar = new javax.swing.JButton();
        Bmodificar = new javax.swing.JButton();
        Blistar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Beliminar = new javax.swing.JButton();
        Blimpiar = new javax.swing.JButton();
        Bactivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Lcliente_id.setText("cliente_id");

        Tcliente_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tcliente_idActionPerformed(evt);
            }
        });

        Lnombre.setText("nombre");

        Lemail.setText("email");

        Ldireccion.setText("direccion");

        Ltelefono.setText("telefono");

        Ttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtelefonoActionPerformed(evt);
            }
        });

        Bguardar.setText("Guardar");
        Bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BguardarActionPerformed(evt);
            }
        });

        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        Bmodificar.setText("Modificar");
        Bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarActionPerformed(evt);
            }
        });

        Blistar.setText("Listar");
        Blistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "cliente_id", "nombre", "email", "direccion", "telefono", "estado"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Beliminar.setText("Eliminar");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        Blimpiar.setText("limpiar");
        Blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarActionPerformed(evt);
            }
        });

        Bactivar.setText("Activar");
        Bactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lnombre)
                                        .addComponent(Lemail)
                                        .addComponent(Ldireccion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ltelefono)
                                        .addGap(6, 6, 6)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tnombre)
                                    .addComponent(Temail)
                                    .addComponent(Tdireccion)
                                    .addComponent(Ttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lcliente_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Tcliente_id)))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Beliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(Bactivar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Blistar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Blimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lcliente_id)
                            .addComponent(Tcliente_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bguardar)
                            .addComponent(Bactivar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lnombre)
                            .addComponent(Tnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Bbuscar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lemail)
                            .addComponent(Temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ldireccion)
                            .addComponent(Tdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Beliminar)
                            .addComponent(Ltelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Bmodificar)))
                .addGap(18, 18, 18)
                .addComponent(Blimpiar)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Blistar)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tcliente_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tcliente_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tcliente_idActionPerformed

    private void BguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BguardarActionPerformed

        
        int resultado = cont.insertarCliente(Tcliente_id.getText(), Ttelefono.getText(), Temail.getText(), Tdireccion.getText(), Tnombre.getText(), "Activo");
        if (resultado != -1) {
            JOptionPane.showMessageDialog(this,
                    "El cliente se guardo con exito",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
            llenarT();
        } else {
            JOptionPane.showMessageDialog(this,
                    "El cliente no se pudo guardar",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        }
       
    }//GEN-LAST:event_BguardarActionPerformed

    private void BlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistarActionPerformed
        llenarTabla(cont.listarClientes());
    }//GEN-LAST:event_BlistarActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
        String[] cliente = cont.consultarCliente(Tcliente_id.getText());
        if (cliente[0] != null) {
            llenarClienteT(cliente);
        } else {
            JOptionPane.showMessageDialog(this,
                    "cliente no encontrado",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BbuscarActionPerformed

    private void BmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarActionPerformed
        int resultado = cont.modificarCliente(Tcliente_id.getText(), Ttelefono.getText(), Temail.getText(), Tdireccion.getText(), Tnombre.getText());
        if (resultado != -1) {
            JOptionPane.showMessageDialog(this,
                    "El cliente se modifico con exito",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
            llenarClienteT(cont.consultarCliente(Tcliente_id.getText()));
        } else {
            JOptionPane.showMessageDialog(this,
                    "El cliente no se pudo modificar",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BmodificarActionPerformed

    private void TtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtelefonoActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed

        int result = cont.borrarCliente(Tcliente_id.getText());
        if (result != -1) {
            JOptionPane.showMessageDialog(this,
                    "cliente eliminado exitosamente",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
            llenarTabla(cont.listarClientes());
        } else {
            JOptionPane.showMessageDialog(this,
                    "El cliente no se pudo eliminar",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_BeliminarActionPerformed

    private void BlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarActionPerformed
        Tcliente_id.setText("");
        Tnombre.setText("");
        Temail.setText("");
        Ttelefono.setText("");
        Tdireccion.setText("");
    }//GEN-LAST:event_BlimpiarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!Tabla.getBounds().contains(evt.getPoint())) {
            Tabla.clearSelection();
        }
    }//GEN-LAST:event_formMouseClicked

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        if (Tabla.getSelectedRow() != -1) {
            int row = Tabla.getSelectedRow();
            Tcliente_id.setText(String.valueOf(Tabla.getValueAt(row, 0)));
            Tnombre.setText(String.valueOf(Tabla.getValueAt(row, 1)));
            Temail.setText(String.valueOf(Tabla.getValueAt(row, 2)));
            Tdireccion.setText(String.valueOf(Tabla.getValueAt(row, 3)));
            Ttelefono.setText(String.valueOf(Tabla.getValueAt(row, 4)));

        }
    }//GEN-LAST:event_TablaMouseClicked

    private void BactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactivarActionPerformed
         int result=cont.ActivarCliente(Tcliente_id.getText());
         if(result!=-1){
         JOptionPane.showMessageDialog(this,
                    "cliente Activado exitosamente",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
            llenarClienteT(cont.consultarCliente(Tcliente_id.getText()));
            
         }else{
         JOptionPane.showMessageDialog(this,
                    "El cliente no se pudo eliminar",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_BactivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PgestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PgestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PgestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PgestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PgestionarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bactivar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Beliminar;
    private javax.swing.JButton Bguardar;
    private javax.swing.JButton Blimpiar;
    private javax.swing.JButton Blistar;
    private javax.swing.JButton Bmodificar;
    private javax.swing.JLabel Lcliente_id;
    private javax.swing.JLabel Ldireccion;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Ltelefono;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Tcliente_id;
    private javax.swing.JTextField Tdireccion;
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Tnombre;
    private javax.swing.JTextField Ttelefono;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
